record internal-metadata {
    name: string,
    value: list<u8>
}

record internal-message {
    body: option<list<u8>>,
    metadata: list<internal-metadata>
}

record internal-subject-message {
    message: internal-message,
    subject: option<string>,
    broker: option<string>
}

variant outcome {
    publish(list<internal-subject-message>),
    error(string)
}

handle-message: func(message: internal-subject-message) -> outcome
