record internal-message {
    message: list<u8>,
    subject: string,
    broker: string
}

record internal-output-message {
    message: list<u8>,
    subject: option<string>,
    broker: option<string>
}

variant outcome {
    publish(list<internal-output-message>),
    error(string)
}

handle-message: func(message: internal-message) -> outcome
